// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kalshiflow/orderbook/v1/snapshot.proto

package orderbookpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotPayload is the inner payload of a kalshi.snapshot_1s envelope.
// market_ticker and event_ts are NOT duplicated here — the outer Envelope
// already carries them. Keeping the inner narrow is how this stream's wire
// shrinks ~70% vs the JSON predecessor.
type SnapshotPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Side           string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`
	Top1PriceUnits int64                  `protobuf:"varint,2,opt,name=top1_price_units,json=top1PriceUnits,proto3" json:"top1_price_units,omitempty"`
	Top1Size       int64                  `protobuf:"varint,3,opt,name=top1_size,json=top1Size,proto3" json:"top1_size,omitempty"`
	Top2PriceUnits *int64                 `protobuf:"varint,4,opt,name=top2_price_units,json=top2PriceUnits,proto3,oneof" json:"top2_price_units,omitempty"`
	Top2Size       *int64                 `protobuf:"varint,5,opt,name=top2_size,json=top2Size,proto3,oneof" json:"top2_size,omitempty"`
	EmitReason     string                 `protobuf:"bytes,6,opt,name=emit_reason,json=emitReason,proto3" json:"emit_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapshotPayload) Reset() {
	*x = SnapshotPayload{}
	mi := &file_kalshiflow_orderbook_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotPayload) ProtoMessage() {}

func (x *SnapshotPayload) ProtoReflect() protoreflect.Message {
	mi := &file_kalshiflow_orderbook_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotPayload.ProtoReflect.Descriptor instead.
func (*SnapshotPayload) Descriptor() ([]byte, []int) {
	return file_kalshiflow_orderbook_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotPayload) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *SnapshotPayload) GetTop1PriceUnits() int64 {
	if x != nil {
		return x.Top1PriceUnits
	}
	return 0
}

func (x *SnapshotPayload) GetTop1Size() int64 {
	if x != nil {
		return x.Top1Size
	}
	return 0
}

func (x *SnapshotPayload) GetTop2PriceUnits() int64 {
	if x != nil && x.Top2PriceUnits != nil {
		return *x.Top2PriceUnits
	}
	return 0
}

func (x *SnapshotPayload) GetTop2Size() int64 {
	if x != nil && x.Top2Size != nil {
		return *x.Top2Size
	}
	return 0
}

func (x *SnapshotPayload) GetEmitReason() string {
	if x != nil {
		return x.EmitReason
	}
	return ""
}

var File_kalshiflow_orderbook_v1_snapshot_proto protoreflect.FileDescriptor

const file_kalshiflow_orderbook_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"&kalshiflow/orderbook/v1/snapshot.proto\x12\x17kalshiflow.orderbook.v1\"\x81\x02\n" +
	"\x0fSnapshotPayload\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\x12(\n" +
	"\x10top1_price_units\x18\x02 \x01(\x03R\x0etop1PriceUnits\x12\x1b\n" +
	"\ttop1_size\x18\x03 \x01(\x03R\btop1Size\x12-\n" +
	"\x10top2_price_units\x18\x04 \x01(\x03H\x00R\x0etop2PriceUnits\x88\x01\x01\x12 \n" +
	"\ttop2_size\x18\x05 \x01(\x03H\x01R\btop2Size\x88\x01\x01\x12\x1f\n" +
	"\vemit_reason\x18\x06 \x01(\tR\n" +
	"emitReasonB\x13\n" +
	"\x11_top2_price_unitsB\f\n" +
	"\n" +
	"_top2_sizeBMZKgithub.com/paulschick/kalshiflow-pipeline/internal/orderbook/orderbookpb;orderbookpbb\x06proto3"

var (
	file_kalshiflow_orderbook_v1_snapshot_proto_rawDescOnce sync.Once
	file_kalshiflow_orderbook_v1_snapshot_proto_rawDescData []byte
)

func file_kalshiflow_orderbook_v1_snapshot_proto_rawDescGZIP() []byte {
	file_kalshiflow_orderbook_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_kalshiflow_orderbook_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kalshiflow_orderbook_v1_snapshot_proto_rawDesc), len(file_kalshiflow_orderbook_v1_snapshot_proto_rawDesc)))
	})
	return file_kalshiflow_orderbook_v1_snapshot_proto_rawDescData
}

var file_kalshiflow_orderbook_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kalshiflow_orderbook_v1_snapshot_proto_goTypes = []any{
	(*SnapshotPayload)(nil), // 0: kalshiflow.orderbook.v1.SnapshotPayload
}
var file_kalshiflow_orderbook_v1_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kalshiflow_orderbook_v1_snapshot_proto_init() }
func file_kalshiflow_orderbook_v1_snapshot_proto_init() {
	if File_kalshiflow_orderbook_v1_snapshot_proto != nil {
		return
	}
	file_kalshiflow_orderbook_v1_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kalshiflow_orderbook_v1_snapshot_proto_rawDesc), len(file_kalshiflow_orderbook_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kalshiflow_orderbook_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_kalshiflow_orderbook_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_kalshiflow_orderbook_v1_snapshot_proto_msgTypes,
	}.Build()
	File_kalshiflow_orderbook_v1_snapshot_proto = out.File
	file_kalshiflow_orderbook_v1_snapshot_proto_goTypes = nil
	file_kalshiflow_orderbook_v1_snapshot_proto_depIdxs = nil
}
