// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kalshiflow/envelope/v1/envelope.proto

package envelopepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the canonical wire format for kalshiflow Pub/Sub topics.
// Field names match internal/envelope/schema.json (snake_case), which drives
// the BigQuery table schema via infra/bigquery.tf. The proto-vs-BQ-schema
// drift detector test pins the contract.
//
// Timestamps are int64 microseconds since Unix epoch. PS schema registry
// rejects external imports (no google.protobuf.Timestamp). BQ Storage Write
// API maps proto int64 to TIMESTAMP columns as micros-since-epoch.
//
// raw_payload is bytes. For the snapshot_1s stream it carries a marshalled
// SnapshotPayload. For trade, lifecycle, settlement it carries UTF-8 JSON
// bytes of the raw Kalshi message body.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeId    string                 `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	EventTs       int64                  `protobuf:"varint,2,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`          // micros since epoch
	IngestedTs    int64                  `protobuf:"varint,3,opt,name=ingested_ts,json=ingestedTs,proto3" json:"ingested_ts,omitempty"` // micros since epoch
	KalshiTs      *int64                 `protobuf:"varint,4,opt,name=kalshi_ts,json=kalshiTs,proto3,oneof" json:"kalshi_ts,omitempty"` // micros since epoch
	Seq           *int64                 `protobuf:"varint,5,opt,name=seq,proto3,oneof" json:"seq,omitempty"`
	SnapshotSeq   *int64                 `protobuf:"varint,6,opt,name=snapshot_seq,json=snapshotSeq,proto3,oneof" json:"snapshot_seq,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	SeriesId      string                 `protobuf:"bytes,8,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	ContractId    *string                `protobuf:"bytes,9,opt,name=contract_id,json=contractId,proto3,oneof" json:"contract_id,omitempty"`
	MarketTicker  *string                `protobuf:"bytes,10,opt,name=market_ticker,json=marketTicker,proto3,oneof" json:"market_ticker,omitempty"`
	RawPayload    []byte                 `protobuf:"bytes,11,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_kalshiflow_envelope_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_kalshiflow_envelope_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_kalshiflow_envelope_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *Envelope) GetEventTs() int64 {
	if x != nil {
		return x.EventTs
	}
	return 0
}

func (x *Envelope) GetIngestedTs() int64 {
	if x != nil {
		return x.IngestedTs
	}
	return 0
}

func (x *Envelope) GetKalshiTs() int64 {
	if x != nil && x.KalshiTs != nil {
		return *x.KalshiTs
	}
	return 0
}

func (x *Envelope) GetSeq() int64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Envelope) GetSnapshotSeq() int64 {
	if x != nil && x.SnapshotSeq != nil {
		return *x.SnapshotSeq
	}
	return 0
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *Envelope) GetContractId() string {
	if x != nil && x.ContractId != nil {
		return *x.ContractId
	}
	return ""
}

func (x *Envelope) GetMarketTicker() string {
	if x != nil && x.MarketTicker != nil {
		return *x.MarketTicker
	}
	return ""
}

func (x *Envelope) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

var File_kalshiflow_envelope_v1_envelope_proto protoreflect.FileDescriptor

const file_kalshiflow_envelope_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"%kalshiflow/envelope/v1/envelope.proto\x12\x16kalshiflow.envelope.v1\"\xb3\x03\n" +
	"\bEnvelope\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\x12\x19\n" +
	"\bevent_ts\x18\x02 \x01(\x03R\aeventTs\x12\x1f\n" +
	"\vingested_ts\x18\x03 \x01(\x03R\n" +
	"ingestedTs\x12 \n" +
	"\tkalshi_ts\x18\x04 \x01(\x03H\x00R\bkalshiTs\x88\x01\x01\x12\x15\n" +
	"\x03seq\x18\x05 \x01(\x03H\x01R\x03seq\x88\x01\x01\x12&\n" +
	"\fsnapshot_seq\x18\x06 \x01(\x03H\x02R\vsnapshotSeq\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1b\n" +
	"\tseries_id\x18\b \x01(\tR\bseriesId\x12$\n" +
	"\vcontract_id\x18\t \x01(\tH\x03R\n" +
	"contractId\x88\x01\x01\x12(\n" +
	"\rmarket_ticker\x18\n" +
	" \x01(\tH\x04R\fmarketTicker\x88\x01\x01\x12\x1f\n" +
	"\vraw_payload\x18\v \x01(\fR\n" +
	"rawPayloadB\f\n" +
	"\n" +
	"_kalshi_tsB\x06\n" +
	"\x04_seqB\x0f\n" +
	"\r_snapshot_seqB\x0e\n" +
	"\f_contract_idB\x10\n" +
	"\x0e_market_tickerBJZHgithub.com/paulschick/kalshiflow-pipeline/internal/envelope/envelopepb;envelopepbb\x06proto3"

var (
	file_kalshiflow_envelope_v1_envelope_proto_rawDescOnce sync.Once
	file_kalshiflow_envelope_v1_envelope_proto_rawDescData []byte
)

func file_kalshiflow_envelope_v1_envelope_proto_rawDescGZIP() []byte {
	file_kalshiflow_envelope_v1_envelope_proto_rawDescOnce.Do(func() {
		file_kalshiflow_envelope_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kalshiflow_envelope_v1_envelope_proto_rawDesc), len(file_kalshiflow_envelope_v1_envelope_proto_rawDesc)))
	})
	return file_kalshiflow_envelope_v1_envelope_proto_rawDescData
}

var file_kalshiflow_envelope_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kalshiflow_envelope_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: kalshiflow.envelope.v1.Envelope
}
var file_kalshiflow_envelope_v1_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kalshiflow_envelope_v1_envelope_proto_init() }
func file_kalshiflow_envelope_v1_envelope_proto_init() {
	if File_kalshiflow_envelope_v1_envelope_proto != nil {
		return
	}
	file_kalshiflow_envelope_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kalshiflow_envelope_v1_envelope_proto_rawDesc), len(file_kalshiflow_envelope_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kalshiflow_envelope_v1_envelope_proto_goTypes,
		DependencyIndexes: file_kalshiflow_envelope_v1_envelope_proto_depIdxs,
		MessageInfos:      file_kalshiflow_envelope_v1_envelope_proto_msgTypes,
	}.Build()
	File_kalshiflow_envelope_v1_envelope_proto = out.File
	file_kalshiflow_envelope_v1_envelope_proto_goTypes = nil
	file_kalshiflow_envelope_v1_envelope_proto_depIdxs = nil
}
