#!/usr/bin/env python3
"""Aggregate a Cloud Monitoring NDJSON export into the small metrics file the showcase page reads.

Input is the output of the monitoring export (one NDJSON file per workload.googleapis.com metric, each line a
timeSeries object). Cumulative counters are turned into deltas per (labels, resource, startTime) epoch, so
in-place restarts and the HOL-111 start_time resets do not double-count. Only aggregates are written; no
project, node, or instance identifiers reach the output.

Usage: python3 scripts/showcase_metrics.py <export-data-dir> site/metrics.js
"""

import collections
import datetime as dt
import json
import pathlib
import sys


def load(data_dir, name):
    with open(data_dir / f"{name}.ndjson") as f:
        return [json.loads(line) for line in f]


def parse_ts(s):
    return dt.datetime.fromisoformat(s.replace("Z", "+00:00"))


def counter_deltas(series_list, window_start):
    """Yield (end_time, labels, delta) for every cumulative INT64 point."""
    for ts in series_list:
        labels = ts["metric"].get("labels", {})
        by_start = collections.defaultdict(list)
        for p in ts["points"]:
            iv = p["interval"]
            by_start[iv["startTime"]].append((iv["endTime"], int(p["value"]["int64Value"])))
        for start, pts in by_start.items():
            pts.sort()
            prev = None
            # First point of an epoch that began inside the window is its own delta (count since start).
            if parse_ts(start) >= window_start:
                prev = 0
            for end, v in pts:
                if prev is not None and v >= prev:
                    yield parse_ts(end), labels, v - prev
                prev = v


def main():
    data_dir = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[2])

    msgs = load(data_dir, "ws_messages_received_total")
    all_ends = [parse_ts(p["interval"]["endTime"]) for ts in msgs for p in ts["points"]]
    window_start, window_end = min(all_ends), max(all_ends)
    first_day = window_start.date() + dt.timedelta(days=1)  # drop partial edge days
    last_day = window_end.date() - dt.timedelta(days=1)

    def in_days(t):
        return first_day <= t.date() <= last_day

    daily = collections.defaultdict(lambda: collections.Counter())
    for t, labels, d in counter_deltas(msgs, window_start):
        if in_days(t):
            daily[t.date().isoformat()][labels.get("stream", "")] += d

    streams = ["orderbook_delta", "trade", "lifecycle", "settlement"]
    days = []
    day = first_day
    while day <= last_day:
        c = daily.get(day.isoformat(), collections.Counter())
        days.append({"date": day.isoformat(), **{s: c.get(s, 0) for s in streams}})
        day += dt.timedelta(days=1)

    by_hour = [0] * 24
    stalls_total = 0
    for t, _, d in counter_deltas(load(data_dir, "ws_data_stall_force_reconnects_total"), window_start):
        if in_days(t):
            by_hour[t.hour] += d
            stalls_total += d

    reconnects = sum(
        d for t, _, d in counter_deltas(load(data_dir, "ws_reconnects_total"), window_start) if in_days(t)
    )

    snapshots = collections.Counter()
    for t, labels, d in counter_deltas(load(data_dir, "bookkeeper_snapshots_emitted_total"), window_start):
        if in_days(t):
            snapshots[labels.get("reason", "")] += d

    exported = sum(
        d
        for t, labels, d in counter_deltas(load(data_dir, "parquet_rows_exported_total"), window_start)
        if in_days(t) and labels.get("venue") == "kalshi"
    )

    result = {
        "window": {"from": first_day.isoformat(), "to": last_day.isoformat(), "days": len(days)},
        "daily_messages": days,
        "stall_reconnects_by_utc_hour": by_hour,
        "totals": {
            "ws_messages": sum(sum(d[s] for s in streams) for d in days),
            "snapshots_change": snapshots["change"],
            "snapshots_heartbeat": snapshots["heartbeat"],
            "ws_reconnects": reconnects,
            "stall_reconnects": stalls_total,
            "stall_reconnects_07_10z": sum(by_hour[7:10]),
            "parquet_rows_exported_kalshi": exported,
        },
    }
    out.write_text("// Generated by scripts/showcase_metrics.py; do not edit.\nwindow.METRICS = "
                   + json.dumps(result, indent=1) + ";\n")
    print(json.dumps(result["totals"], indent=1), result["window"], file=sys.stderr)


if __name__ == "__main__":
    main()
